branch-defaults:
  default:
    environment: null
  main:
    environment: dev-env
environment-defaults:
  dev-env:
    branch: main
    repository: re-hello-world-repo
global:
  application_name: hello-world-app
  branch: main
  default_ec2_keyname: aws-eb-re
  default_platform: Node.js 18
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: re-hello-world-repo
  sc: git
  workspace_type: Application
