version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     java: corretto11
  post_build:
    commands:
      # - unzip hello-world-app/app-*.zip 2>&1 > /var/log/hello-world_last_deploy.log
      - npm install
    # artifacts:
    #   files:
    #     - hello-world-app/app-*.zip
    #     - .ebextensions/**/*
        
artifacts:
  files:
    - .ebextensions/**/*
    - .platform/**/*
#     - src/**/*
#     - package.json